name: Hello world workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  goodbye:
    runs-on: ubuntu-latest
      steps:
        - name: goodbye world
          run: echo "Goodbye world"
          shell: bash
