# testing merge on the main branch after a pullrequest approval
name: On add new forecast requests

on: 
  pull_request:
    branches: [ main ]
    
jobs:
  authenticate-user:
    runs-on: ubuntu-latest
    permissions: write-all
      
    steps:
      - name: test request
        id: authentication-step
      # testing pull request number that will be used later on in the process
        run: |
          echo 'Pull request received'
          echo 'Commit message: ${{ github.event.head_commit.message }}'          
          echo 'Number: ${{ github.event.pull_request.number }}'
          echo "pr-number=${{ github.event.pull_request.number }}" >> "$GITHUB_OUTPUT"
          
          
      - name: Approve request
        uses: juliangruber/approve-pull-request-action@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.authentication-step.outputs.pr-number }}
          
#       - name: Merge changes
#         # subsequent steps can access the following output:
#         # commit - The commit sha of this PR merged
#         uses: juliangruber/merge-pull-request-action@v1
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           number: 1
#           method: squash # merge rebase
#           repo: juliangruber/octokit-action
        
  
