# testing merge on the main branch after a pullrequest approval
name: Merge on Pull request 
on: 
  pull_request_target:
    branches: [ main ]
    
jobs:
  # Firts authenticate user based on PR details
  authenticate_user:
    runs-on: ubuntu-latest
    
    steps:    
      - name: dump info
        run: |
          echo ">>> Repo: ${{ github.repository }}"
          echo ">>> SrcPath: $GITHUB_WORKSPACE"
          

      # Checkout the repo
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Collect PR details
        id: collect_details
        run: |
          echo "gh_actor=${{ github.actor }}" >> $GITHUB_OUTPUT
          
      - name: Get changes
        id: get_changed_files
        uses: tj-actions/changed-files@v36
        
        # Debug only step
      - name: List all changed files
        run: |
          for file in ${{ steps.get_changed_files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
          
      - name: Execute Verify Access script
        env:
          local_test_var: "MyLocalValue"
          calling_actor: ${{ steps.collect_details.outputs.gh_actor }}
          changed_files: ${{ steps.get_changed_files.outputs.all_changed_files }}
          
        run: python ./.github/scripts/verify_access.py
