# testing merge on the main branch after a pullrequest approval
name: On Pull request testing

on: 
  pull_request_target:
    branches: [ main ]
    
jobs:
  authenticate-user:
    runs-on: ubuntu-latest
    permissions: write-all
      
    steps:
      # GET DETAILS 
      - name: get pull request details
        id: get-datails
        run: |
          echo 'Pull request received'
          echo "gh-actor=${{ github.actor }}" >> "$GITHUB_OUTPUT"
          echo "gh-repo=${{ github.repository }}" >> "$GITHUB_OUTPUT"
          echo "pr-number=${{ github.event.pull_request.number }}" >> "$GITHUB_OUTPUT"
    
    
      # GET CHANGES 
      # ------------
      # Checkout the repo
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      # Verify what changed 
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v36
        
      # Debug only step
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

          
      # Autenthicate with python 
      - name: Execute Verify Access script
        env: 
          Test_Parameter: ${{ github.actor }}
        
        run: python ./.github/scripts/verify_access.py

    
          
      - name: Approve request
        uses: juliangruber/approve-pull-request-action@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.authentication-step.outputs.pr-number }}

      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.13.1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
          UPDATE_LABELS: ""
          LOG: "DEBUG"
#       - name: Merge changes
#         # subsequent steps can access the following output:
#         # commit - The commit sha of this PR merged
#         uses: juliangruber/merge-pull-request-action@v1
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           number: ${{ steps.authentication-step.outputs.pr-number }}
#           method: squash # merge rebase
#           repo: juliangruber/octokit-action
