# This is a basic workflow to help you get started with Actions

name: On Update

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab [TEST ONLY - TO BE REMOVED ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  update:
    runs-on: ubuntu-latest
    
    steps:
    
      # First step is to update locals
      - name: checkout repo
        uses: actions/checkout@v3 # checkout the repository content
        
        
      # Then set up python to be used later on
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
  
      # Let's get some more details about this event
      # First of all, let's get 
      - name: get user info 
        id: users
        env:
          MyUserName: 'Pippo'
#           MyUserName: ${{ github.event.sender }}
        run: echo $MyUserName
        
      
      - name: get push files details
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'


  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
