# testing merge on the main branch
name: PushFromPTest


on: 
  workflow_run:
    workflows: [ TriggeringWF ]
    types: [completed]
    branches: [ ptest ]
    
#   push:
#     branches: [ ptest ]
    
permissions: write-all

jobs:
  merge-ptest-to-main:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v3 # checkout the repository content

      - name: Set git config
        run: |
          echo '<<<<<<<<<<<< PushFromPTest triggered >>>>>>>>>>>>>>'
          echo '${{ toJSON(github.ref) }}'
          git config --local user.email "paolo.milano@isi.it"
          git config --local user.name "M-7th"      

#          git config --local user.email "action@github.com"
#          git config --local user.name "GitHub Action"      
      - name: Merge to main        
        run: |
          git fetch --unshallow
          git checkout main
          git pull
          git merge --no-ff origin/ptest -m "Auto-merge ptest back to main"
          git push
