# testing merge on the main branch
name: PushFromPTest


on: 
  workflow_run:
    workflows: [ TriggeringWF ]
    types: [completed]
    branches: [ ptest ]



jobs:
  test_job:
    name: Test job n.1
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Set git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Step merge
        run: |
          git fetch --unshallow
          git pull
          git switch main
          git merge origin/ptest

 
