name: Test
on:
  # scheduled submission every Wednesday at 1.30 a.m. 
  # schedule:
  #   - cron: '30 5 * * 3'  

  workflow_dispatch:

  
jobs:
  test_job:
    runs-on: ubuntu-latest
    env:
      run_import: 'go'
    
    steps:
     - name: dump var value
       run: echo "Var value is $run_import"
       
     - name: change the var value
       run: echo "run_import = 'no go'" >> $GITHUB_ENV

     - name: dump var value after change
       run: echo "Var value is $run_import"
