name: Test
on:
  schedule:
    - cron: '10 16 * * 1'
    - cron: '10 16 * * 5'
    - cron: '30 16 * * 5'

  workflow_dispatch:
     inputs:
       myInput:
         description: 'User Input:'
         required: true
         default: "Hello World"
  
jobs:
  test_job:
    runs-on: ubuntu-latest
    env:
      run_import: 'vai'
    
    steps:
      # Checkout the python tools repo
      # -------------------------------------------      
      - name: checkout python tools repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: 'Testing-Forecast-Actions/Testing-Tools'
          ref: 'main'
          path: './tools/'


      # Checkout the python tools repo
      # -------------------------------------------      
      - name: checkout python tools repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: 'european-modelling-hubs/hub-tools'
          ref: 'main'
          path: './emh-tools/'

      # Checkout the data repository
      # -------------------------------------------      
      - name: checkout data repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: 'Testing-Forecast-Actions/TEST'
          ref: 'main'
          path: './repo/'

      - name: change the var value
        run: |
          # INPUT_STORE=${{ github.event_name == 'pull_request' }} python ./tools/code/test_code.py
          INPUT_STORE=${{ github.event.schedule != '10 16 * * 1' }} python ./tools/code/test_code.py
