# testing merge on the main branch
name: ptest to main


on: 
  push:
    branches: [ ptest ]
    
permissions: write-all

jobs:
  merge-ptest-to-main:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v3 # checkout the repository content

#       - name: Set git config
#         run: |
#           git config --global user.email "paolo.milano@isi.it"
#           git config --global user.name "M-7th"
      
      - name: Merge to main
        run: |
          git fetch --unshallow
          git checkout main
          git pull
          git merge --no-ff ptest -m "Auto-merge ptest back to main"
          git push
