name: Test
on:
  # scheduled submission every Wednesday at 1.30 a.m. 
  # schedule:
  #   - cron: '30 5 * * 3'  

  workflow_dispatch:

  
jobs:
  scheduled-submit:
    runs-on: ubuntu-latest
    
    steps:
     - name: pippo
       run: |
         echo ">>> Repo: ${{ github.repository }}"
         echo ">>> Owner: ${{ github.repository_owner }}"
