name: Weekly Submission

on:
  # scheduled submission every Wednesday at 1.30 a.m. 
  schedule:
    - cron: '30 5 * * 3'  

jobs:
  scheduled-submit:
    runs-on: ubuntu-latest
    
    steps:
      # Get the list of changes from a json file 
      - name: Get changes list
        run: |
        id: get_changes
          echo "Read changes list from json"
    
      # Trigger server-side updating and UI deploy
      # --------------------------------------------
      # WEBHOOK
      - name: Invoke deployment hook
        env:
          webhook_url: ${{ secrets.WEB_HOOK_URL_DEV }}
          # webhook_url: ${{ secrets.WEBHOOK_URL }}
          # webhook_url: ${{ secrets.WEB_HOOK_URL_PRODUCTION }}
          webhook_secret: ${{ secrets.WEB_HOOK_SECRET }}
          #data: '{ "changes": ${{ toJSON(needs.validate_request.outputs.changed_files) }}, "actor" : ${{ toJSON(github.actor) }} }'
          data: ${{ get_changes.outputs.changes_list }}

        run: |
          echo ">>> Calling custom webhook"
          pip install requests
          echo ">>> Pip installed" 
          python ./tools/.github/scripts/utils/workflow_webhook.py
